os:
    - linux
    - osx

dist: xenial

sudo: required

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq; fi

install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install llvm; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -qq flex bison clang lld-6.0; fi

language: c

script:
    - sh ./.ci_build_samples.sh
